### ISSUE TITLE
Top navbar - All icon links redirect to github

### ISSUE THREAD

**Issue by lukyncze** [ivenuss/docsum#1]
I found out that all icon links in navbar basically redirects user on the same page - your Github profile.

![image](https://user-images.githubusercontent.com/36028726/225595500-f89934b4-a4f1-468b-b93b-10cb236453ff.png)

**Comment by ivenuss** [comment]
Yeah, this whole project was just for a test and they can be replaced by your own links.

**Comment by lukyncze** [comment]
In that case, sorry, I thought this was a serious project.
